// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xalxduxbivbthiyusadj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhbHhkdXhiaXZidGhpeXVzYWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNjI3NDUsImV4cCI6MjA3MjYzODc0NX0.HAoc8xk_3xXeF5pml0PaQpyLpcD8fl8UUsb0QCYv3TA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});